#!/usr/bin/env bash

alias mvn="mvn -Djava.awt.headless=true"

function join_by {
    local d=$1
    shift
    echo -n $1
    shift
    printf "%s" "${@/#/$d}"
}

#
# Kerberos
#

export NAME=d.otroshchenko

alias kinit='kinit -e aes128-cts-hmac-sha1-96'
alias kinit-full="kinit $NAME@CRITEOIS.LAN"
alias kloc="kinit $NAME"
alias kreinit='kdestroy && klist && kinit && klist'
alias openssl_brew=/usr/local/opt/openssl/bin/openssl

#
# Hadoop
#

HADOOP_COMMANDS_TO_ALIAS=(
    'test'
    'appendToFile'
    'cat'
    'chown'
    'copyFromLocal'
    'copyToLocal'
    'count'
    'cp'
    'du'
    'dus'
    'get'
    'ls'
    'mkdir'
    'moveFromLocal'
    'mv'
    'put'
    'rm'
    'rmr'
    'stat'
    'tail'
    'text'
    'touchz'
)
for cmd in ${HADOOP_COMMANDS_TO_ALIAS[@]}; do
    ALIAS_CMD="alias h$cmd=\"hadoop fs -$cmd\""
    eval $ALIAS_CMD
done

function hpcat {
    hadoop fs -text $1 | sed 's/^...../0a/' | xxd -p -r
}

function pailcat {
    hdfs dfs -text $1 | sed 's/^...../0a/' | xxd -p -r
}

function pa4pre_from_pa4() {
    CMD="hadoop distcp -m100 ${@:3} hdfs://pa4$1 $2"
    eval $CMD
}

function pa4_from_am5() {
    CMD="hadoop distcp -skipcrccheck -m100 ${@:3} webhdfs://am5$1 $2"
    eval $CMD
}


alias ylist="yarn application -list"
alias ystatus="yarn application -status"
alias ykill="yarn application -kill"
alias ylogs="yarn logs -applicationId"

function dm() {
    project_root=$(git rev-parse --show-toplevel)
    python "$project_root/manage.py" $@
}

alias dmnb='dm shell_plus --notebook'

#
# JMOAB
#

# Required by Maven
export GIT_SSH=`which ssh`

function bootstrapgit() {
    gitdir=$(git rev-parse --git-dir)
    scp -p -P 29418 $NAME@review.criteois.lan:hooks/commit-msg ${gitdir}/hooks/
}

function fixjmoab {
    if [ ! -f pom.xml ]; then
        echo 'pom.xml not found.'
    else
        echo 'Deleting pom.xml.'
        rm pom.xml
    fi

    mvn bfs:create-pom -DmaxRetries=20
    mvn bfs:refresh-moab -DmaxRetries=20
    mvn bfs:refresh-sources
}

function nukemaven {
    read -p "Do you really want to nuke da maven (y/n)? " CONT
    if [ "$CONT" = "y" ]; then
        echo "FAIA1111111"
        rm -rf "~/.m2/repository"
    else
        echo "Later then..."
    fi
}

alias refresh-moab='mvn bfs:refresh-moab'
alias refresh-sources='mvn bfs:refresh-sources'
alias deploy='mvn clean install -DpackageForDeploy'

function moab_checkout() {
    PROJECTS=$(join_by , $@)
    mvn bfs:checkout -Dprojects=$PROJECTS
}

# vagrant

function vagrant_run() {
    SCRIPT_PATH=$1
    shift
    vagrant scp $SCRIPT_PATH .
    echo "./$SCRIPT_PATH $@" | vagrant ssh -- -t
}

# For thrift

export PATH="/usr/local/opt/bison/bin:$PATH"
export PATH="/usr/local/opt/thrift@0.90/bin:$PATH"
